name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    uses: trailofbits/.github/.github/workflows/lint.yml@ww/reusable-demo
    permissions:
      checks: write
    with:
      type: rust
      cargo-sort: true
