on:
  release:
    types:
      - published

name: release

jobs:
  crate:
    runs-on: ubuntu-latest
    steps:
      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17
          sudo apt install -y libpolly-17-dev

      - uses: actions/checkout@v3

      - name: login
        run: echo ${{ secrets.CRATES_IO_TOKEN }} | cargo login

      - name: publish
        run: cargo publish
